#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

INPUT=$1
OUTPUT=${INPUT%.ne}.js

echo "Building grammar"
npx nearleyc $INPUT -o $OUTPUT
echo "Linting output"
set +e
eslint --fix $OUTPUT &> /dev/null
set -e
sed -i '1s/^/\/* eslint-disable *\/\n/' $OUTPUT